#!/usr/bin/env node
'use strict'

/*
 * provision-offline — onboard ONE tenant to offline mode in a single command.
 *
 *   node provision-offline.js --tenant <tenantId> --uri "<boss-mongo-uri>" [--db womoladb]
 *
 * It:
 *   1. exports the tenant's data slice (the seed),
 *   2. writes a ready-to-use nazbu.env for the shop (tenant, room, full mode),
 *   3. prints the exact steps for the shop + the boss node.
 *
 * Everything is derived from the tenantId — no per-tenant code, ever.
 */

const fs = require('fs')
const path = require('path')
const { execFileSync } = require('child_process')

function arg (n, d) {
  const i = process.argv.indexOf('--' + n)
  if (i >= 0 && process.argv[i + 1]) return process.argv[i + 1]
  return d
}

const tenant = arg('tenant')
const uri = arg('uri')
const db = arg('db', 'womoladb')
// Global (tenant-less) lookup collections to seed whole. The shop's own tenant
// doc is always included automatically.
const globals = arg('globals', 'exchangerates,plans')
// Unique per-shop code → offline document numbers (SLE/PO/…) can't collide.
const shopCode = arg('shop-code', tenant ? 'S' + tenant.slice(-4) : 'SHOP1')
const out = arg('out', path.join('offline-bundles', tenant || 'tenant'))
if (!tenant || !uri) {
  console.error('usage: node provision-offline.js --tenant <tenantId> --uri "<boss-mongo-uri>" [--db womoladb]')
  process.exit(1)
}

const room = 'tenant-' + tenant
const seedDir = path.join(out, 'seed')
fs.mkdirSync(out, { recursive: true })

// 1. Export the tenant's slice.
console.log(`\n▸ Exporting tenant ${tenant}…`)
execFileSync('node', [path.join(__dirname, 'seed.js'), 'export', '--tenant', tenant, '--uri', uri, '--db', db, '--out', seedDir, '--globals', globals], { stdio: 'inherit' })

// 2. Generate the shop's nazbu.env.
const env = `# Auto-generated by provision-offline for tenant ${tenant}
NAZBU_TENANT=${tenant}
NAZBU_ROOM=${room}
NAZBU_FULL=1
NAZBU_DB=${db}
NAZBU_INTERNET=1
# Set this to the SHOP's local Mongo (same shape as Womola's DB_URI):
NAZBU_URI=mongodb://<user>:<pass>@mongo:27017/${db}?authSource=admin&directConnection=false
`
fs.writeFileSync(path.join(out, 'nazbu.env'), env)

// 3. Print the steps.
console.log(`
✔ Bundle ready at ${out}/

── In the SHOP (fresh install) ──────────────────────────────
0. In the shop's Womola BACKEND env (womola_be/.env.prod) set:
     SHOP_CODE=${shopCode}                         # collision-free offline doc numbers
     LICENSE_ENFORCEMENT=on                         # lock the app when the licence expires
     LICENSE_SERVER_URL=https://womola.com/api      # phones home to renew when online
     LICENSE_PUBLIC_KEY="<from scripts/gen-license-keys.sh>"   # verifies keys OFFLINE
     HUB_KEY=<one-time key from /sa → Licence → Register hub>  # heartbeat auth
   (Online deployments leave LICENSE_ENFORCEMENT unset = unchanged.)
1. Install Womola locally (Docker) so its Mongo is running.
2. Load the tenant's data:
     node nazbu-mongo/seed.js import --uri "<shop-mongo-uri>" --db ${db} --in ${seedDir}
3. Fill ${out}/nazbu.env  (set NAZBU_URI to the shop's DB_URI), then run the sidecar:
     node nazbu-mongo/run.js --full --room ${room} --tenant ${tenant} --internet \\
          --uri "<shop-mongo-uri>" --db ${db}

── On the BOSS (VPS, once) ──────────────────────────────────
   node nazbu-mongo/run.js --full --room ${room} --tenant ${tenant} --internet \\
        --uri "<boss-mongo-uri>" --db ${db}

Same room + same tenant → the shop runs 100% offline and reconciles with the
boss whenever the internet is available. No central server.
`)
